AWSTemplateFormatVersion: "2010-09-09"
Description: Secrets Manager secret for RDS

Parameters:
  DBUsername:
    Type: String
  DBPassword:
    Type: String

Resources:
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: miniblog/db-credentials
      Description: Credentials for RDS instance
      SecretString: !Sub |
        {
          "username": "${DBUsername}",
          "password": "${DBPassword}"
        }

Outputs:
  SecretArn:
    Value: !Ref DBSecret
